apiVersion: v1
kind: ConfigMap
metadata:
  name: collabspace-config
  namespace: collabspace
data:
  NODE_ENV: production
  LOG_LEVEL: warn
  AUTH_SERVICE_URL: http://auth-service.collabspace.svc.cluster.local:4002
  DOC_SERVICE_URL: http://doc-service.collabspace.svc.cluster.local:4003
  CODE_SERVICE_URL: http://code-service.collabspace.svc.cluster.local:4004
  BOARD_SERVICE_URL: http://board-service.collabspace.svc.cluster.local:4005
  PROJECT_SERVICE_URL: http://project-service.collabspace.svc.cluster.local:4006
  NOTIFICATION_SERVICE_URL: http://notification-service.collabspace.svc.cluster.local:4007
  AI_SERVICE_URL: http://ai-service.collabspace.svc.cluster.local:4008
  REDIS_URL: redis://redis.collabspace.svc.cluster.local:6379
  KAFKA_BROKERS: kafka-0.kafka-headless.collabspace.svc.cluster.local:9092,kafka-1.kafka-headless.collabspace.svc.cluster.local:9092,kafka-2.kafka-headless.collabspace.svc.cluster.local:9092
  JAEGER_ENDPOINT: http://jaeger.collabspace.svc.cluster.local:14268/api/traces
  JWT_EXPIRY: "15m"
  JWT_REFRESH_EXPIRY: "7d"
  AI_MODEL: gpt-4o
  AI_MAX_TOKENS: "4096"
  SMTP_PORT: "587"
  SMTP_FROM: noreply@collabspace.io
