apiVersion: v1
kind: Service
metadata:
  name: code-service
  namespace: collabspace
  labels:
    app.kubernetes.io/name: code-service
    app.kubernetes.io/part-of: collabspace
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4004
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: code-service
