apiVersion: v1
kind: Namespace
metadata:
  name: collabspace
  labels:
    app.kubernetes.io/part-of: collabspace
    app.kubernetes.io/managed-by: kustomize
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: "[]"
