// Types
export type {
  User,
  UserPreferences,
  Organization,
  OrganizationSettings,
  OrganizationMember,
  Workspace,
  Document,
  DocumentCollaborator,
  CodeFile,
  WhiteboardData,
  WhiteboardElement,
  Viewport,
  Project,
  Task,
  TaskComment,
  Sprint,
  Comment,
  Reaction,
  Notification,
  AIMessage,
  AIMessageMetadata,
  ToolCall,
  AIAgent,
  WebSocketEvent,
  CRDTUpdate,
  AuditLog,
  Permission,
  PaginatedResponse,
  ApiResponse,
  TaskStatus,
  TaskPriority,
  SprintStatus,
  AgentType,
  AgentStatus,
  NotificationType,
  PermissionAction,
} from './types/index.js';

// Event types
export type {
  BaseEvent,
  DocumentEvent,
  DocumentCreatedPayload,
  DocumentUpdatedPayload,
  DocumentDeletedPayload,
  CollaboratorJoinedPayload,
  CollaboratorLeftPayload,
  CodeEvent,
  FileCreatedPayload,
  FileUpdatedPayload,
  ExecutionStartedPayload,
  ExecutionCompletedPayload,
  ProjectEvent,
  TaskCreatedPayload,
  TaskUpdatedPayload,
  SprintStartedPayload,
  SprintCompletedPayload,
  AIEvent,
  AgentStartedPayload,
  AgentCompletedPayload,
  SuggestionGeneratedPayload,
  SystemEvent,
  UserConnectedPayload,
  UserDisconnectedPayload,
  SystemErrorPayload,
  AppEvent,
  EventType,
  EventPayload,
} from './types/events.js';

// Constants
export {
  KAFKA_TOPICS,
  REDIS_KEYS,
  WS_EVENTS,
  PERMISSIONS,
  RATE_LIMITS,
  hasPermission,
  MAX_DOCUMENT_SIZE,
  MAX_FILE_SIZE,
  MAX_UPLOAD_SIZE,
  MAX_COLLABORATORS,
  MAX_WORKSPACES_FREE,
  MAX_WORKSPACES_PRO,
  MAX_WORKSPACES_ENTERPRISE,
  MAX_MEMBERS_FREE,
  MAX_MEMBERS_PRO,
  MAX_MEMBERS_ENTERPRISE,
  MAX_TASKS_PER_PROJECT,
  MAX_SPRINTS_PER_PROJECT,
  MAX_AI_CONVERSATION_LENGTH,
  MAX_AI_TOKENS_PER_REQUEST,
  MAX_COMMENT_LENGTH,
  MAX_DOCUMENT_TITLE_LENGTH,
  MAX_WORKSPACE_NAME_LENGTH,
  MAX_LABEL_LENGTH,
  MAX_LABELS_PER_TASK,
  MAX_SUBTASKS,
  MAX_WHITEBOARD_ELEMENTS,
  MAX_CODE_FILE_SIZE,
  SESSION_TTL_SECONDS,
  REFRESH_TOKEN_TTL_SECONDS,
  CACHE_TTL_SECONDS,
  PRESENCE_TTL_SECONDS,
  LOCK_TTL_SECONDS,
  AI_REQUEST_TIMEOUT_MS,
  CODE_EXECUTION_TIMEOUT_MS,
  CRDT_DEBOUNCE_MS,
  SEARCH_DEBOUNCE_MS,
} from './constants/index.js';

export type { KafkaTopic, WSEvent, Role, PermAction, RateLimitConfig } from './constants/index.js';

// Utils
export {
  generateId,
  slugify,
  retry,
  debounce,
  throttle,
  deepMerge,
  validateEmail,
  hashString,
  formatBytes,
  parseJSON,
  chunk,
  omit,
  pick,
  clamp,
  sleep,
} from './utils/index.js';

// Errors
export {
  AppError,
  NotFoundError,
  UnauthorizedError,
  ForbiddenError,
  ValidationError,
  ConflictError,
  RateLimitError,
  isAppError,
} from './utils/errors.js';

// Logger
export { createLogger } from './utils/logger.js';
export type { Logger, LogLevel, LogEntry, LoggerOptions } from './utils/logger.js';

// Crypto
export {
  encrypt,
  decrypt,
  hashPassword,
  verifyPassword,
  generateToken,
  generateKeyPair,
} from './utils/crypto.js';
export type { EncryptedData, KeyPair } from './utils/crypto.js';
