apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: collabspace
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: collabspace
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4008
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ai-service
